### ISSUE TITLE
Errors when trying to add tap

### ISSUE THREAD

**Issue by marc-brouard** [brunoluiz/homebrew-tap#1]
`
❯ brew tap  brunoluiz/homebrew-tap                                                         
==> Tapping brunoluiz/tap
Cloning into '/usr/local/Homebrew/Library/Taps/brunoluiz/homebrew-tap'...
remote: Enumerating objects: 124, done.
remote: Counting objects: 100% (124/124), done.
remote: Compressing objects: 100% (89/89), done.
remote: Total 124 (delta 47), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (124/124), 16.03 KiB | 713.00 KiB/s, done.
Resolving deltas: 100% (47/47), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/brunoluiz/homebrew-tap/Formula/jornada.rb
jornada: Calling bottle :unneeded is disabled! There is no replacement.
Please report this issue to the brunoluiz/tap tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/brunoluiz/homebrew-tap/Formula/jornada.rb:9

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/brunoluiz/homebrew-tap/Formula/pwa-server.rb
pwa-server: Calling bottle :unneeded is disabled! There is no replacement.
Please report this issue to the brunoluiz/tap tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/brunoluiz/homebrew-tap/Formula/pwa-server.rb:6

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/brunoluiz/homebrew-tap/Formula/go-pwa-server.rb
go-pwa-server: Calling bottle :unneeded is disabled! There is no replacement.
Please report this issue to the brunoluiz/tap tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/brunoluiz/homebrew-tap/Formula/go-pwa-server.rb:6

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/brunoluiz/homebrew-tap/Formula/urlzap.rb
urlzap: Calling bottle :unneeded is disabled! There is no replacement.
Please report this issue to the brunoluiz/tap tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/brunoluiz/homebrew-tap/Formula/urlzap.rb:6

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/brunoluiz/homebrew-tap/Formula/flaggio-cleaner-bot.rb
flaggio-cleaner-bot: Calling bottle :unneeded is disabled! There is no replacement.
Please report this issue to the brunoluiz/tap tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/brunoluiz/homebrew-tap/Formula/flaggio-cleaner-bot.rb:6

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/brunoluiz/homebrew-tap/Formula/mermaid-server.rb
mermaid-server: Calling bottle :unneeded is disabled! There is no replacement.
Please report this issue to the brunoluiz/tap tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/brunoluiz/homebrew-tap/Formula/mermaid-server.rb:6

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/brunoluiz/homebrew-tap/Formula/goaccess-pixel.rb
goaccess-pixel: Calling bottle :unneeded is disabled! There is no replacement.
Please report this issue to the brunoluiz/tap tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/brunoluiz/homebrew-tap/Formula/goaccess-pixel.rb:6

Error: Cannot tap brunoluiz/tap: invalid syntax in tap!
`

**Comment by brunoluiz** [comment]
Thanks for reporting! It seems it is something related to the deprecation of a certain feature used by `brew`. I removed the offending line (`bottle :unneeded`) and it should be fixed now.

You might need to run `brew update` before trying to tap.
